### ISSUE TITLE
Client functions return Axios Responses

### ISSUE THREAD

**Issue by rtirserio** [drone/drone-node#16]
The responses returned from the Client are the Axios responses rather than just the data from the response. I'm happy to PR the changes but wanted to be sure there wasn't a reason for this before doing the work. 

I am really enjoying Drone. Keep up the great work

**Comment by tboerger** [comment]
What else would you expect? I have returned the response to also be able to handle error responses. I'm open for improvements.

**Comment by rtirserio** [comment]
If the purpose of this module is to abstract away the underlying implementation of interacting with the API then I would expect to be returned the relevant data or any errors that would be raised by communicating with the API. Any HTTP response parsing or error handling could be handled in a standard way across all the functions to ease the burden on the implementor.

**Comment by tboerger** [comment]
As I said, I'm open for improvements. I have just written something up to date to start implementing a hubot plugin. I'm not an experienced javascript developer :)

**Comment by rtirserio** [comment]
Sounds good. I'll get a PR together for you to review.
