### ISSUE TITLE
Suggestion: TypeScript definitions

### ISSUE THREAD

**Issue by colelawrence** [drone/drone-node#5]
Hello, I would like to suggest that some form of TypeScript definitions be shipped with this library, because having the definitions can provide an incredible experience for developers who either already use TypeScript or devs who have tooling that can take advantage of the definitions. Putting them in this repository specifically would allow for API updates to remain in sync with their definitions.

**Comment by devth** [comment]
+1

**Comment by colelawrence** [comment]
As @DanielRosenwasser mentioned in a similar issue I opened on webpack/tapable, these definitions would be good to add to the DefinitelyTyped repo, outside of this repository. So then, the drone team does not need to worry about supporting the definitions.
I don't know what the protocol is for where definition issues should exist (in the base repo or in DefinitelyTyped)...

**Comment by tboerger** [comment]
Since nobody of the core team is writing/using typescript I will close this issue for now as it's out of focus.
